### ISSUE TITLE
Question: Should we change the .bat file to .cmd

### ISSUE THREAD

**Issue by qqiumax** [michaelliu1210/michaelliu1210.github.io#2]
I have no idea, just a thought

**Comment by michaelliu1210** [comment]
> Edit

but why

**Comment by michaelliu1210** [comment]
> [<img alt="@qqiumax" width="40" height="40" src="https://avatars.githubusercontent.com/u/102963434?s=88&amp;v=4">](/qqiumax)



> I have no idea, just a thought

Isnt bat file and cmd the same?

**Comment by michaelliu1210** [comment]
> I have no idea, just a thought

bat用的是16位的dos运行的，而cmd则是通过XP系统的32位dos运行的，有些命令在bat里面是可以使用的，但是cmd文件里面却不能使用。from baidu

**Comment by qqiumax** [comment]
Idk, it was just an idea.
________________________________
